### ISSUE TITLE
US-align cant read pdb files 

### ISSUE THREAD

**Issue by aemiol** [pylelab/USalign#9]
Hi,
US-align is unable to read pdb files from https://esmatlas.com/ . An example is attached. I keep getting "ERROR! Too few residues: 0 residues (<=3)"
[test.txt](https://github.com/pylelab/USalign/files/10221750/test.txt)

**Comment by kad-ecoli** [comment]
This is caused by incorrect atom name justification in the PDB files provided by ESM Atlas. As shown in https://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#ATOM, the 4-character atom name for CA atom in column 13-16 should be " CA " rather than "CA  " (please mind the space). To work around this issue, you can use the option ``-atom "CA  "``. For example, 

```bash
$ USalign test.txt test.txt -atom "CA  "

Name of Structure_1: test.txt:A (to be superimposed onto Structure_2)
Name of Structure_2: test.txt:A
Length of Structure_1: 120 residues
Length of Structure_2: 120 residues

Aligned length= 120, RMSD=   0.00, Seq_ID=n_identical/n_aligned= 1.000
TM-score= 1.00000 (normalized by length of Structure_1: L=120, d0=4.05)
TM-score= 1.00000 (normalized by length of Structure_2: L=120, d0=4.05)
(You should use TM-score normalized by length of the reference structure)

(":" denotes residue pairs of d < 5.0 Angstrom, "." denotes other aligned residues)
LINRKVVEALLQRLGVDLVSVGDGKQAVDRITGGDWPDVVLMDIQMPVMDGLEATRSIRAWELEAEQTGRPRLPIVALTAGAFASERVRCSEAGMDDFLAKPIDREQLSAVLQRWLGDAA
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
LINRKVVEALLQRLGVDLVSVGDGKQAVDRITGGDWPDVVLMDIQMPVMDGLEATRSIRAWELEAEQTGRPRLPIVALTAGAFASERVRCSEAGMDDFLAKPIDREQLSAVLQRWLGDAA
```
Alternatively, if you are only aligning monomeric protein chain, you can use the Fortran version of TMalign at https://zhanggroup.org/TM-align/TMalign.f which should generate identical result.

**Comment by kad-ecoli** [comment]
Commit b1a14602d0a25df09cbbc6af8543b104b78a50d8 now includes a c++ program [pdbAtomName](https://github.com/pylelab/USalign/blob/master/pdbAtomName.cpp) that fix incorrect atom name justification for pdb file, such as those downloaded from ESM atlas.

**Comment by aemiol** [comment]
Thanks !!
